# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3596c4885e13e8043960d126721b9cdbf21cf13a6d8e3d5dd2ab332e86eea93defd0af611188ee54520276a4127425804301f139bd9887cefad26c0622e3630f

test:
  secret_key_base: 11492a84b6572b3a217ced8253bc11884a129a35e38020c185da3f1e5ef2883df06aea0216084e038d5cab005c6bccf7f2295d7b1eaff40392020ae58fc7bbc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
